// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ViUTWqJ28pbCm-QwDVZwnRhEIFnJdSQ',
    appId: '1:637076318434:web:e4de4904b4bf3cba2216bb',
    messagingSenderId: '637076318434',
    projectId: 'liveasy-39f1c',
    authDomain: 'liveasy-39f1c.firebaseapp.com',
    storageBucket: 'liveasy-39f1c.appspot.com',
    measurementId: 'G-Y3XMZ7YKWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCleeyoL5Nt1ktm0yJ8TXFPLknwL6cholc',
    appId: '1:637076318434:android:26a18ee3f89585672216bb',
    messagingSenderId: '637076318434',
    projectId: 'liveasy-39f1c',
    storageBucket: 'liveasy-39f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIm4x6KzBOqpWHJOKR7Z7YXzMiOaLZs4k',
    appId: '1:637076318434:ios:6bd2a52d06668fb42216bb',
    messagingSenderId: '637076318434',
    projectId: 'liveasy-39f1c',
    storageBucket: 'liveasy-39f1c.appspot.com',
    androidClientId: '637076318434-oi8mtf9b6qe8tgg9fugg38e2u3f14clg.apps.googleusercontent.com',
    iosClientId: '637076318434-rr76qc3q020jldu3f48ccq8ln494bs16.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveasy',
  );
}
